#! /usr/bin/env bash
set -eu

[[ ${DOCKER_TAG} =~ ^chainer([0-9ab.]+)-(devel|devel-minimal)$ ]]
CHAINER=${BASH_REMATCH[1]}
DOCKER_DIR=${BASH_REMATCH[2]}

docker build --build-arg CHAINER=${CHAINER} -t ${IMAGE_NAME} ${DOCKER_DIR}
